### ISSUE TITLE
Request Kernel Patching Support for Nethunter

### ISSUE THREAD

**Issue by MrX0r** [Yasir-siddiqui/android_kernel_xiaomi_lavender#1]
YasiR Siddiquip

Can you please add these kernel features for the support of "NetHunter"

wiki
https://gitlab.com/kalilinux/nethunter/build-scripts/kali-nethunter-project/wikis/home

1. HID attacks
2. Wi-Fi injection
-  kernel supports HID interface (HID USB Keyboard & Mouse support)
-  kernel supports mac80211 (Aircrack-ng 802.11 frames inject patch)

Modifying the Kernel
https://gitlab.com/kalilinux/nethunter/build-scripts/kali-nethunter-project/wikis/Modifying-the-Kernel

```
Patching

By default, we use the mac80211 injection patch.  You can apply this patch as follows:

wget http://patches.aircrack-ng.org/mac80211.compat08082009.wl_frag+ack_v1.patch
patch -p1 < mac80211.compat08082009.wl_frag+ack_v1.patch

Other patches are HID patches for keyboard support and CDROM patch
https://github.com/pelya/android-keyboard-gadget
```

Thank you very much

**Comment by MrX0r** [comment]
I have briefly tested your kernel with MAC80211 support, it comes to various completions.

MAC80211 support is important for "Nethunter"

I used lavender-perf_defconfig with CONFIG_MAC80211 = y and your build.sh

  ```
CC      net/mac80211/tx.o
../net/mac80211/tx.c: In function 'ieee80211_duration':
../net/mac80211/tx.c:167:8: error: 'IEEE80211_BAND_60GHZ' undeclared (first use in this function)
   case IEEE80211_BAND_60GHZ:
        ^
../net/mac80211/tx.c:167:8: note: each undeclared identifier is reported only once for each function it appears in
../net/mac80211/tx.c:152:3: warning: enumeration value 'NL80211_BAND_60GHZ' not handled in switch [-Wswitch]
   switch (sband->band) {
   ^
```
FIX:
**mac80211/tx.c**
https://github.com/Yasir-siddiqui/android_kernel_xiaomi_lavender/blob/fc3923b5e26029a35a06e10666abffc5fb24166b/net/mac80211/tx.c#L167
 case NL80211_BAND_60GHZ:

https://github.com/Yasir-siddiqui/android_kernel_xiaomi_lavender/blob/fc3923b5e26029a35a06e10666abffc5fb24166b/net/mac80211/mlme.c#L1343
case NL80211_BAND_60GHZ:

**I hope you can eliminate the mistakes**

**Comment by Yasir-siddiqui** [comment]
:O thanks

**Comment by Yasir-siddiqui** [comment]
Did you successfully added that?

**Comment by MrX0r** [comment]
> Did you successfully added that?

Hello Yasir-siddiqui

Yes I am still working on it, I still have problems with the modules they are not loading.

[nethunter_lavender_defconfig.txt](https://github.com/Yasir-siddiqui/android_kernel_xiaomi_lavender/files/3839692/nethunter_lavender_defconfig.txt)

[dmesg.log](https://github.com/Yasir-siddiqui/android_kernel_xiaomi_lavender/files/3839715/dmesg.log)

**There are still many mistakes.**

Maybe you can see where the error is in the log

![Screenshot_2019-11-12-18-57-09-791_com offsec nhterm](https://user-images.githubusercontent.com/54841800/68738653-2ab04200-05e7-11ea-9fa6-8487e62c2a92.jpg)
![Screenshot_2019-11-12-19-25-21-667_com offsec nhterm](https://user-images.githubusercontent.com/54841800/68738655-2ab04200-05e7-11ea-9dc0-42de277ce384.jpg)

I think various support is still missing in the kernel

There is a problem with the drivers and firmware

  Android and the kernel took advantage

  "/ etc / firmware"
  "/ Vendor / firmware"

But Nethunter does not know that

**Comment by MrX0r** [comment]
YasiR Siddiquip

but yeah nethunter doesn't really have any support for system-as-root-partition

Can we fix that somehow? do you have any idea??

**Comment by Yasir-siddiqui** [comment]
I literally have no idea ;__;

**Comment by Yasir-siddiqui** [comment]
Sad RiP

**Comment by MrX0r** [comment]
> Sad RiP

So the kernel works with Nethunter there are only problems with the Nethunter APP, I am currently working with the support team to fix various bugs. And make compatible.

we do not give up so fast;)

**Comment by khajiitvaper2017** [comment]
Maybe use Oneplus 7 as base? https://forum.xda-developers.com/oneplus-7-pro/development/rom-kali-nethunter-oneplus-7-oneplus-7-t3976357/amp/

**Comment by MrX0r** [comment]
@Yasir-siddiqui 

```
    #enable depmod/modprobe support in rootfs
    if [ ! "$(mountpoint $mnt/lib/modules 2> /dev/null | grep 'is a')" ]; then
       $busybox mount -r -o bind /system/lib/modules $mnt/lib/modules && bklog "[+] mounted /lib/modules"
    fi
```

For Nethunter you have to put  /vendor/lib/modules in /system/lib/modules

Kali Nethunter needs the data in /lib/modules

How can we customize the script?

I've been using a symlink /system/lib/modules /vendor/lib/modules file in the init.rc file but no success.

https://source.android.com/devices/architecture/kernel/loadable-kernel-modules

**Comment by Yasir-siddiqui** [comment]
> @Yasir-siddiqui
> 
> ```
>     #enable depmod/modprobe support in rootfs
>     if [ ! "$(mountpoint $mnt/lib/modules 2> /dev/null | grep 'is a')" ]; then
>        $busybox mount -r -o bind /system/lib/modules $mnt/lib/modules && bklog "[+] mounted /lib/modules"
>     fi
> ```
> 
> For Nethunter you have to put /vendor/lib/modules in /system/lib/modules
> 
> Kali Nethunter needs the data in /lib/modules
> 
> How can we customize the script?
> 
> I've been using a symlink /system/lib/modules /vendor/lib/modules file in the init.rc file but no success.
> 
> https://source.android.com/devices/architecture/kernel/loadable-kernel-modules

You can use in ramdisk, make a script and push in rc file

**Comment by MrX0r** [comment]
> > @Yasir-siddiqui 
> You can use in ramdisk, make a script and push in rc file

Okay, now everything is working Nethunter APP  is working with the kernel. Now there are some small errors.

usb / wifi problems (I am using a rt2800usb Wifi)

Can it be that the OTG needs more power? ([  290.039062] get prop 149 is not supported in usb)
I have to order an OTG-Y cable

**issues**

**We don't know the algorithms for LPM for this host, disabling LPM.**
**get prop 149 is not supported in usb**

```
Line 6297: [   63.282826] usb usb2: SerialNumber: xhci-hcd.0.auto
	Line 6297: [   63.282826] usb usb2: SerialNumber: xhci-hcd.0.auto
	Line 6300: [   63.600084] usb 1-1: new high-speed USB device number 2 using xhci-hcd
	Line 6301: [   63.757777] usb 1-1: New USB device found, idVendor=0b05, idProduct=17e8
	Line 6302: [   63.757799] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
	Line 6303: [   63.757812] usb 1-1: Product: 802.11 n WLAN
	Line 6304: [   63.757823] usb 1-1: Manufacturer: Ralink
	Line 6305: [   63.757833] usb 1-1: SerialNumber: 1.0
	Line 6330: [   68.299242] PMI: smblib_update_usb_type: lct battery charge APSD=UNKNOWN PD=0
	Line 6331: [   68.299807] get prop 149 is not supported in usb
```

[nethunter_lavender_defconfig.txt](https://github.com/Yasir-siddiqui/android_kernel_xiaomi_lavender/files/3894212/nethunter_lavender_defconfig.txt)

maybe you see in the config what I forgot to activate

dmesg
[log.txt](https://github.com/Yasir-siddiqui/android_kernel_xiaomi_lavender/files/3894454/log.txt)

**Comment by Yasir-siddiqui** [comment]
Tf, I'm closing this issue it's just getting spammed.
